### ISSUE TITLE
Strange results running the extension on GitHub runners

### ISSUE THREAD

**Issue by rajbos** [github/gh-projects#52]
``` yaml
jobs:
  add-issue:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   
   - name: install the extension
     run: gh extension install github/gh-projects
     env:
      GH_TOKEN: ${{ github.token }}
      
   - name: Test project CLI
     env:
      GH_TOKEN: ${{ secrets.PAT_GH }} # token that has access to the org and projects
     run: gh projects list --org XpiritBV --limit 10
```

## Result:
``` yaml
Usage:
open /dev/tty: no such device or address
  projects item-add [number] [flags]

Examples:

# add an item to the current user's project 1
gh projects item-add 1 --user "@me" --url https://github.com/cli/go-gh/issues/1
```

That `dev/tty` is weird and not the expected result.
